#!/usr/bin/env python3
"""Generate lcos-base /usr/share/lcos/xorg/amdgpu-pre-vega.ids (LCOS #115/#118).

Usage: gen-amdgpu-pre-vega-ids.py <linux-src-root> > amdgpu-pre-vega.ids

Takes every explicit {0x1002, 0xDDDD, ..., CHIP_x} entry of pciidlist[] in
drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c whose CHIP_x sorts before
CHIP_VEGA10 in enum amd_asic_type (include/drm/amd_asic_type.h), i.e.
SI, CIK, VI (Topaz..Stoney), Polaris 10/11/12 and VegaM. The list is closed:
AMD makes no new pre-GFX9 chips, so any amdgpu device NOT in it is GFX9+.
"""
import re, sys, collections
root = sys.argv[1]
drv = open(f"{root}/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c").read()
enum = open(f"{root}/include/drm/amd_asic_type.h").read()
order = re.findall(r'(CHIP_[A-Z0-9_]+)\s*(?:=\s*0)?,',
                   enum.split('enum amd_asic_type {')[1].split('};')[0])
idx = {c: i for i, c in enumerate(order)}
V = idx['CHIP_VEGA10']
body = drv[drv.index('static const struct pci_device_id pciidlist[] = {'):]
body = body[:body.index('};')]
ents = re.findall(r'\{\s*0x1002,\s*0x([0-9A-Fa-f]{4}),[^}]*?(CHIP_[A-Z0-9_]+)[^}]*\}', body)
by = collections.defaultdict(set)
for d, c in ents:
    by[d.lower()].add(c)
for d, s in by.items():
    if len({idx[c] < V for c in s}) > 1:
        sys.exit(f"ambiguous id {d}: {s}")
pre = sorted((d, sorted(s)[0]) for d, s in by.items() if all(idx[c] < V for c in s))
ver = re.search(r'^VERSION = (\d+)\nPATCHLEVEL = (\d+)\nSUBLEVEL = (\d+)',
                open(f"{root}/Makefile").read(), re.M)
print("# LCOS lcos-base: AMD PCI device IDs (vendor 0x1002) that the amdgpu kernel")
print("# driver handles as pre-Vega (CHIP_TAHITI..CHIP_VEGAM: SI, CIK, VI, Polaris,")
print("# VegaM). On these, LCOS installs NO modesetting snippet (0.8 behaviour).")
print("# Any other device bound to amdgpu is treated as Vega/GFX9 or newer.")
if ver:
    print(f"# Generated by packaging/tools/gen-amdgpu-pre-vega-ids.py from Linux "
          f"{ver.group(1)}.{ver.group(2)}.{ver.group(3)} amdgpu_drv.c pciidlist.")
print(f"# {len(pre)} IDs. Format: <device-id lowercase hex> <CHIP_ family>")
for d, c in pre:
    print(f"{d} {c}")
