#!/bin/sh
set -e
# Rewrite LCOS identity files on the installed target.
# Does NOT overwrite a user-chosen /etc/hostname from the users page.
cat > /etc/os-release <<'OS'
PRETTY_NAME="LCOS 0.9"
NAME="LCOS"
VERSION_ID="0.9"
VERSION="0.9 (excalibur)"
VERSION_CODENAME=excalibur
ID=lcos
ID_LIKE="devuan debian"
HOME_URL="https://lunduke.com"
SUPPORT_URL="https://lunduke.com"
BUG_REPORT_URL="https://lunduke.com"
OS
mkdir -p /usr/lib
cp -f /etc/os-release /usr/lib/os-release
printf "%s\n" "LCOS 0.9 \\n \\l" > /etc/issue
printf "%s\n" "LCOS 0.9" > /etc/issue.net
if [ ! -s /etc/hostname ]; then
	printf "%s\n" "LCOS" > /etc/hostname
fi
